"""
File parsing and manipulation utilities for CrysAlisPro experiments.

This module provides functions and classes for:
- Parsing reflection tables (.tab files) and powder patterns (.dat files)
- Computing shell statistics from diffraction data
- Reading and writing experiment metadata
- Managing XML parameter files for data reduction (ProffitXML) and finalization (FinalizationXML)
- Parsing and writing CSV results from the CrysAlisPro ED result viewer
"""

import configparser
import csv
import hashlib
import os
from dataclasses import dataclass, field, fields, asdict
from time import sleep
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional, Tuple, Union
import warnings
import numpy as np
import xml.etree.ElementTree as ET
from glob import glob

if TYPE_CHECKING:
    from cap_auto.cap_control import CAPInstance


# ============================================================================
# Constants
# ============================================================================

_FOM_DICT = {
    'Rint': 1,
    'Rurim': 2,
    'Rpim': 3,
    'Sigma': 4,
    'SigmaA': 5,
    'SigmaB': 6,
    'CC 1/2': 7,
    'CC*': 8,
    'deltaCC': 9,
    'Rsym': 11,
    'RshelX': 12
}


# ============================================================================
# Low-level parsing functions for diffraction data
# ============================================================================

def parse_reflection_table(filename: str, wavelength: float = 0.0251) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Parse a reflection table file (.tab) from CrysAlisPro.
    
    The reflection table is generated by the CAP command:
        WD OLDASCIIT <experiment_path>
    
    This writes peak positions and intensities in a format compatible with the DOS KM4 system.
    
    Args:
        filename: Path to the .tab file
        wavelength: X-ray wavelength in Angstroms (default: 0.0251 for 200keV electrons)
    
    Returns:
        Tuple of (reflections, commands_to_generate):
            reflections: List of dicts with keys:
                - x, y, z: Reciprocal space coordinates
                - R: Reciprocal resolution  
                - I: Intensity
                - centroidx, centroidy: Pixel coordinates on detector
                - d: d-spacing (Angstroms)
                - inv_d: 1/d (inverse Angstroms)
            commands_to_generate: List of CAP commands needed if file is missing
    
    Example:
        >>> reflections, cmds = parse_reflection_table('exp_11317.tab')
        >>> print(f"Found {len(reflections)} reflections")
        >>> print(f"First reflection d-spacing: {reflections[0]['d']:.3f} Å")
    """
    commands_to_generate = ['wd oldasciit "<experiment_path>"']
    
    if not os.path.exists(filename):
        warnings.warn(f"Reflection table file not found: {filename}", UserWarning)
        return [], commands_to_generate
    
    try:
        with open(filename, 'r') as f:
            # Skip header line
            header = f.readline().strip().split()
            
            reflections = []
            for line in f:
                parts = line.strip().split()
                if len(parts) < 11:  # Minimum required columns
                    continue
                
                try:
                    # Parse key columns (indices match the file format)
                    refl = {
                        'x': float(parts[0]),
                        'y': float(parts[1]),
                        'z': float(parts[2]),
                        'R': float(parts[3]),  # Reciprocal resolution
                        'I': float(parts[4]),  # Intensity
                        'centroidx': float(parts[9]),
                        'centroidy': float(parts[10]),
                    }
                    
                    # Compute derived values
                    refl['inv_d'] = refl['R'] / wavelength if wavelength > 0 else 0
                    refl['d'] = 1 / refl['inv_d'] if refl['inv_d'] > 0 else 0
                    
                    reflections.append(refl)
                except (ValueError, IndexError):
                    continue  # Skip malformed lines
        
        return reflections, commands_to_generate
    
    except Exception as e:
        warnings.warn(f"Error parsing reflection table {filename}: {e}", UserWarning)
        return [], commands_to_generate


def parse_powder_pattern(filename: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Parse a powder diffraction pattern file (.dat) from CrysAlisPro.
    
    The powder pattern is generated by the CAP command:
        POWDER RADIAL <bins> <2theta_min> <2theta_max> <azim_min> <azim_max> <output_name>
    
    For example:
        powder radial 128 0.07 15.0 0 360 radial
    
    Args:
        filename: Path to the .dat file
    
    Returns:
        Tuple of (powder_data, commands_to_generate):
            powder_data: List of dicts with keys:
                - two_theta: 2θ angle in degrees
                - d_value: d-spacing in Angstroms
                - intensity: Integrated intensity
                - sigma: Standard deviation
                - count: Number of pixels contributing
                - inv_d: 1/d (inverse Angstroms) [computed]
            commands_to_generate: List of CAP commands needed if file is missing
    
    Example:
        >>> powder, cmds = parse_powder_pattern('radial.dat')
        >>> print(f"Powder pattern has {len(powder)} data points")
        >>> print(f"d-spacing range: {powder[0]['d_value']:.2f} - {powder[-1]['d_value']:.2f} Å")
    """
    commands_to_generate = [
        'powder radial 128 <2theta_min_deg> <2theta_max_deg> 0 360 radial'
    ]
    
    if not os.path.exists(filename):
        warnings.warn(f"Powder pattern file not found: {filename}", UserWarning)
        return [], commands_to_generate
    
    try:
        powder_data = []
        
        with open(filename, 'r') as f:
            # Skip header lines
            f.readline()  # [PowderExtract1dNew 1]
            headers = f.readline().strip().split('\t')
            
            for line in f:
                parts = line.strip().split()
                if len(parts) < 5:
                    continue
                
                try:
                    point = {
                        'two_theta': float(parts[0]),
                        'd_value': float(parts[1]),
                        'intensity': float(parts[2]),
                        'sigma': float(parts[3]),
                        'count': int(parts[4]),
                    }
                    
                    # Compute inverse d-spacing
                    point['inv_d'] = 1 / point['d_value'] if point['d_value'] > 0 else 0
                    
                    powder_data.append(point)
                except (ValueError, IndexError):
                    continue
        
        return powder_data, commands_to_generate
    
    except Exception as e:
        warnings.warn(f"Error parsing powder pattern {filename}: {e}", UserWarning)
        return [], commands_to_generate


# ============================================================================
# Diffraction data analysis class
# ============================================================================

class DiffractionData:
    """Container and analyzer for diffraction data from reflections and powder patterns.
    
    This class provides methods to compute shell statistics and assign shells to
    diffraction data, useful for resolution-dependent analysis.
    
    Args:
        reflections: List of reflection dicts from parse_reflection_table()
        powder: List of powder pattern dicts from parse_powder_pattern()
        wavelength: X-ray wavelength in Angstroms (default: 0.0251 for 200keV electrons)
    
    Example:
        >>> reflections, _ = parse_reflection_table('exp.tab')
        >>> powder, _ = parse_powder_pattern('radial.dat')
        >>> diff_data = DiffractionData(reflections, powder)
        >>> shells = diff_data.compute_shell_statistics()
        >>> for shell in shells:
        ...     print(f"Shell {shell['d_min']:.2f}-{shell['d_max']:.2f} Å: "
        ...           f"{shell['N_peaks']} peaks, ratio={shell['peak_ratio']:.3f}")
    """
    
    def __init__(self, reflections: List[Dict[str, Any]], 
                 powder: List[Dict[str, Any]], 
                 wavelength: float = 0.0251):
        self.reflections = reflections
        self.powder = powder
        self.wavelength = wavelength
        self._shell_boundaries = None
    
    def _suggest_shell_boundaries(self) -> List[float]:
        """Suggest sensible shell boundaries based on data range.
        
        Returns shells in inverse d-spacing (1/Å) from low to high resolution.
        Default strategy: [1/d_max, 1/10, 1/1.2, 1/0.8, 1/(d_min*1.5), 1/d_min]
        
        Returns:
            List of shell boundaries in inverse Angstroms
        """
        if not self.powder:
            return [0.0, 0.1, 0.833, 1.25, 2.0]  # Fallback boundaries
        
        d_values = [p['d_value'] for p in self.powder if p['d_value'] > 0]
        if not d_values:
            return [0.0, 0.1, 0.833, 1.25, 2.0]
        
        d_min = min(d_values)
        d_max = max(d_values)
        
        # Create sensible shell boundaries
        boundaries = [
            1 / d_max,           # Lowest resolution
            1 / 10.0,            # ~10 Å shell
            1 / 1.2,             # ~1.2 Å shell
            1 / 0.8,             # ~0.8 Å shell
            1 / (d_min * 1.5),   # High resolution buffer
            1 / d_min            # Highest resolution
        ]
        
        # Remove duplicates and sort
        boundaries = sorted(list(set(b for b in boundaries if b >= 0)))
        
        return boundaries
    
    def assign_shells(self, shell_boundaries: Optional[List[float]] = None,
                     in_place: bool = True) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
        """Assign shell indices to reflections and powder data.
        
        Args:
            shell_boundaries: List of boundaries in 1/d (Å⁻¹). If None, auto-suggest.
            in_place: If True, modify self.reflections and self.powder; if False, return copies
        
        Returns:
            Tuple of (reflections_with_shells, powder_with_shells)
        """
        if shell_boundaries is None:
            shell_boundaries = self._suggest_shell_boundaries()
        
        self._shell_boundaries = shell_boundaries
        
        # Work on copies if not in_place
        reflections = self.reflections if in_place else [r.copy() for r in self.reflections]
        powder = self.powder if in_place else [p.copy() for p in self.powder]
        
        # Assign shells to reflections
        for refl in reflections:
            inv_d = refl.get('inv_d', 0)
            # Find shell index using digitize logic
            shell_idx = 0
            for i, boundary in enumerate(shell_boundaries[:-1]):
                if boundary <= inv_d < shell_boundaries[i + 1]:
                    shell_idx = i
                    break
            else:
                shell_idx = len(shell_boundaries) - 2 if inv_d >= shell_boundaries[-1] else 0
            refl['shell'] = shell_idx
        
        # Assign shells to powder data
        for point in powder:
            inv_d = point.get('inv_d', 0)
            shell_idx = 0
            for i, boundary in enumerate(shell_boundaries[:-1]):
                if boundary <= inv_d < shell_boundaries[i + 1]:
                    shell_idx = i
                    break
            else:
                shell_idx = len(shell_boundaries) - 2 if inv_d >= shell_boundaries[-1] else 0
            point['shell'] = shell_idx
        
        return reflections, powder
    
    def compute_shell_statistics(self, shell_boundaries: Optional[List[float]] = None) -> List[Dict[str, Any]]:
        """Compute per-shell statistics from reflections and powder data.
        
        Args:
            shell_boundaries: List of boundaries in 1/d (Å⁻¹). If None, auto-suggest.
        
        Returns:
            List of dicts with shell statistics:
                - d_max: Maximum d-spacing in shell (Å)
                - d_min: Minimum d-spacing in shell (Å)
                - I_tot: Total intensity in powder pattern
                - I_peak: Total intensity in reflections
                - N_peaks: Number of reflections
                - peak_ratio: I_peak / I_tot (fraction of intensity in peaks)
        
        Example:
            >>> shells = diff_data.compute_shell_statistics()
            >>> high_res_shell = shells[-1]
            >>> print(f"Highest resolution shell: {high_res_shell['d_min']:.2f} Å")
            >>> print(f"Peak/powder ratio: {high_res_shell['peak_ratio']:.3f}")
        """
        if shell_boundaries is None:
            shell_boundaries = self._suggest_shell_boundaries()
        
        # Assign shells first
        self.assign_shells(shell_boundaries, in_place=True)
        
        shell_stats = []
        
        for shell_idx in range(len(shell_boundaries) - 1):
            # Get d-spacing range for this shell
            inv_d_min = shell_boundaries[shell_idx]
            inv_d_max = shell_boundaries[shell_idx + 1]
            d_max = 1 / inv_d_min if inv_d_min > 0 else float('inf')
            d_min = 1 / inv_d_max if inv_d_max > 0 else 0
            
            # Compute statistics for reflections in this shell
            shell_reflections = [r for r in self.reflections if r.get('shell') == shell_idx]
            I_peak = sum(r.get('I', 0) for r in shell_reflections)
            N_peaks = len(shell_reflections)
            
            # Compute statistics for powder data in this shell
            shell_powder = [p for p in self.powder if p.get('shell') == shell_idx]
            I_tot = sum(p.get('intensity', 0) for p in shell_powder)
            
            # Compute peak ratio
            peak_ratio = I_peak / I_tot if I_tot > 0 else float('nan')
            
            shell_stats.append({
                'd_max': d_max,
                'd_min': d_min,
                'I_tot': I_tot,
                'I_peak': I_peak,
                'N_peaks': N_peaks,
                'peak_ratio': peak_ratio
            })
        
        return shell_stats


# ============================================================================
# CAP file generation helper functions
# ============================================================================

def generate_powder_commands(exp_path: str, wavelength: float = 0.0251,
                            d_min: float = 0.3, d_max: float = 20.0,
                            recenter: bool = True) -> List[str]:
    """Generate CAP commands to create a powder diffraction pattern.
    
    Args:
        exp_path: Path to experiment (without .par extension)
        wavelength: X-ray wavelength in Angstroms
        d_min: Minimum d-spacing in Angstroms
        d_max: Maximum d-spacing in Angstroms
        recenter: Whether to adjust center before extraction
    
    Returns:
        List of CAP commands to execute
    """
    # Convert d-spacing to 2theta in degrees
    two_theta_min = wavelength / d_max * 180 / np.pi
    two_theta_max = wavelength / d_min * 180 / np.pi
    
    cmds = []
    if recenter:
        cmds.append('dc microedadjustcenter')
    
    cmds.append(f'powder radial 128 {two_theta_min:.4f} {two_theta_max:.4f} 0 360 radial')
    
    return cmds


def generate_reflection_commands(exp_path: str, redo_peak_hunt: bool = True) -> List[str]:
    """Generate CAP commands to create a reflection table.
    
    Args:
        exp_path: Path to experiment (without .par extension)
        redo_peak_hunt: Whether to re-run peak hunting before writing
    
    Returns:
        List of CAP commands to execute
    """
    cmds = []
    
    if redo_peak_hunt:
        # Peak hunt with standard parameters
        cmds.append('ph snogui_pars 1000 20 1 0 2 2 10 10 1 0 0 0 0.0 1000.0 0 1 1 1')
    
    # Write peak table in DOS-compatible ASCII format
    cmds.append(f'wd oldasciit "{exp_path}"')
    
    return cmds


def generate_diff_image_commands(exp_path: str) -> Tuple[List[str], str]:
    """Generate CAP commands to create a diffraction image snapshot.
    
    Args:
        exp_path: Path to experiment (without .par extension)
    
    Returns:
        Tuple of (commands, output_filename)
    """
    exp_dir = os.path.dirname(exp_path)
    output_fn = exp_path + '_diff_screen.png'
    
    cmds = []
    
    # Try to find middle frame
    try:
        frame_list = glob(os.path.join(exp_dir, 'frames', '*.rodhypix'))
        if frame_list:
            frame_list.sort(key=lambda fn: int(os.path.splitext(fn)[0].rsplit('_', 1)[-1]))
            middle_frame = frame_list[len(frame_list) // 2]
            cmds.append(f'rd i "{middle_frame}"')
    except Exception:
        pass  # Will use current frame
    
    cmds.append(f'wd pnggiftiff "{output_fn}"')
    
    return cmds, output_fn


# ============================================================================
# High-level diffraction info extraction
# ============================================================================

def get_diff_info(path: str, cap: Optional['CAPInstance'] = None,
                  keep_peak_file: bool = False, keep_powder_file: bool = False,
                  redo_peak_hunt: bool = True, wavelength: float = 0.0251,
                  pow_dmin: float = 0.3, pow_dmax: float = 20.0,
                  recenter_pattern: bool = True,
                  shell_boundaries: Optional[List[float]] = None,
                  log: Optional[Callable[[str], None]] = None) -> Tuple[List[Dict], List[Dict], List[Dict], str]:
    """Extract diffraction information from a CAP experiment.
    
    This function orchestrates the extraction of peak tables, powder patterns,
    and shell statistics. It can optionally generate missing files via CAP commands.
    
    Args:
        path: Path to experiment (without .par extension)
        cap: CAPInstance for generating files. If None, only parse existing files.
        keep_peak_file: Don't regenerate peak file if it exists
        keep_powder_file: Don't regenerate powder file if it exists
        redo_peak_hunt: Re-run peak hunting before writing table
        wavelength: X-ray wavelength in Angstroms
        pow_dmin: Minimum d-spacing for powder pattern (Å)
        pow_dmax: Maximum d-spacing for powder pattern (Å)
        recenter_pattern: Adjust center before extracting powder pattern
        shell_boundaries: Custom shell boundaries in 1/d. If None, auto-suggest.
        log: Logging function (default: print)
    
    Returns:
        Tuple of (shell_statistics, reflections, powder_data, diff_image_path):
            shell_statistics: List of dicts with per-shell statistics
            reflections: List of dicts with reflection data
            powder_data: List of dicts with powder pattern data
            diff_image_path: Path to diffraction image snapshot
    
    Example:
        >>> from cap_auto.cap_control import CAPInstance
        >>> cap = CAPInstance(start_now=True)
        >>> shells, peaks, powder, img = get_diff_info('exp_11317', cap=cap)
        >>> print(f"Found {len(peaks)} reflections")
        >>> print(f"Shell statistics: {len(shells)} shells")
        >>> cap.stop()
    """
    if log is None:
        log = print
    
    powder_fn = os.path.join(os.path.dirname(path), 'radial.dat')
    peak_fn = path + '.tab'
    
    # Determine what needs to be generated
    generate_powder = (not os.path.exists(powder_fn)) or (not keep_powder_file)
    generate_peaks = (not os.path.exists(peak_fn)) or (not keep_peak_file)
    
    # Generate files via CAP if needed and if CAP instance provided
    if cap is not None and (generate_powder or generate_peaks):
        from cap_auto.cap_control import CAPInstance  # Import here to avoid circular dependency
        
        if not isinstance(cap, CAPInstance):
            raise TypeError("cap must be a CAPInstance")
        
        cmds = []
        
        if recenter_pattern and (generate_powder or generate_peaks):
            cmds.append('dc microedadjustcenter')
        
        if generate_powder:
            if os.path.exists(powder_fn):
                log(f"Removing existing powder file: {powder_fn}")
                os.remove(powder_fn)
            cmds.extend(generate_powder_commands(path, wavelength, pow_dmin, pow_dmax, recenter=False))
        
        if generate_peaks:
            if os.path.exists(peak_fn):
                log(f"Removing existing peak file: {peak_fn}")
                os.remove(peak_fn)
            cmds.extend(generate_reflection_commands(path, redo_peak_hunt))
        
        # Execute commands via CAP
        if cmds:
            log(f"Generating files via CAP: {len(cmds)} commands")
            for cmd in cmds:
                result = cap.execute(cmd, timeout=180)
                if not result.success:
                    log(f"Warning: Command failed: {cmd}")
            
            # Wait for files to appear
            max_wait = 20  # seconds
            for fn in [powder_fn, peak_fn]:
                if fn == powder_fn and not generate_powder:
                    continue
                if fn == peak_fn and not generate_peaks:
                    continue
                
                waited = 0
                while not os.path.exists(fn) and waited < max_wait:
                    sleep(0.1)
                    waited += 0.1
                
                if not os.path.exists(fn):
                    log(f"Warning: File not created after {max_wait}s: {fn}")
    
    # Parse files (will return empty lists with warnings if files don't exist)
    reflections, _ = parse_reflection_table(peak_fn, wavelength)
    powder, _ = parse_powder_pattern(powder_fn)
    
    log(f"Parsed {len(reflections)} reflections and {len(powder)} powder points")
    
    # Compute shell statistics
    diff_data = DiffractionData(reflections, powder, wavelength)
    shell_stats = diff_data.compute_shell_statistics(shell_boundaries)
    
    # Generate diffraction image if CAP available
    diff_img_fn = path + '_diff_screen.png'
    if cap is not None:
        try:
            img_cmds, diff_img_fn = generate_diff_image_commands(path)
            for cmd in img_cmds:
                cap.execute(cmd, timeout=30)
        except Exception as e:
            log(f"Could not generate diffraction image: {e}")
    
    return shell_stats, reflections, powder, diff_img_fn


# ============================================================================
# CSV Results Viewer Functions
# ============================================================================

def write_cap_csv(fn: str, ds: List[dict]) -> None:
    """Write experiment results in CrysAlisPro ED result viewer CSV format.
    
    Args:
        fn: Output filename
        ds: List of experiment dicts (all must have same keys)
    
    Example:
        >>> experiments = [{'Experiment name': 'exp1', 'Cell': '10 10 10 90 90 90'}, ...]
        >>> write_cap_csv('results.csv', experiments)
    """
    from textwrap import dedent
    
    with open(fn, 'w', newline='') as fh:
        fh.write(dedent(
            f'''\
            VERSION 1
            HEADER INFO: 
            Number of experiments: {len(ds)}
            Number of columns {len(ds[0])}



            '''
        ))
        writer = csv.DictWriter(fh, fieldnames=ds[0].keys())
        writer.writeheader()
        for experiment in ds:
            writer.writerow(experiment)


def parse_cap_csv(fn: str, use_raw_cell: bool,
                  filter_missing: bool = True) -> Tuple[List[dict], np.ndarray, np.ndarray]:
    """Parse a CSV experiment report file from the CrysAlisPro ED result viewer.
    
    Args:
        fn: Path to CSV file
        use_raw_cell: If True, use 'Current unit cell'; if False, use 'Final SG unit cell'
        filter_missing: If True, filter out experiments with empty cell parameters
    
    Returns:
        Tuple of (experiments, cells, centrings):
            experiments: List of experiment dicts
            cells: Numpy array of cell parameters (N x 6: a, b, c, α, β, γ)
            centrings: Numpy array of centering symbols ('P', 'I', 'F', etc.)
    
    Example:
        >>> exps, cells, centrings = parse_cap_csv('results.csv', use_raw_cell=True)
        >>> print(f"Found {len(exps)} experiments")
        >>> print(f"Cell a-axes: {cells[:, 0]}")
    """
    with open(fn) as fh:
        for _ in range(7):
            _ = fh.readline()
        ds = list(csv.DictReader(fh))
    
    key = 'Current unit cell' if use_raw_cell else 'Final SG unit cell'
    ds = [d for d in ds if d.get(key, '').strip()] if filter_missing else ds
    cells = np.array([d[key].split() for d in ds]).astype(float)
    
    def get_centring(d: dict) -> str:
        if use_raw_cell:
            ctr = d.get('Current lattice', 'P').strip()[-1]
        else:
            ctr = d.get('Space group RED', 'P').strip()[0]
        if ctr not in ['P', 'I', 'F', 'A', 'B', 'C', 'R', 'H']:
            warnings.warn(f'Unknown centring {ctr}. Assuming P')
            ctr = 'P'
        return ctr
    
    centrings = np.array([get_centring(d) for d in ds])
    
    return ds, cells, centrings


# ============================================================================
# Experiment Metadata Parsing
# ============================================================================

def parse_cap_meta(experiments: Union[str, List[str]],
                   log_fun: Optional[Callable[[str], None]] = None,
                   include_merged: bool = False,
                   exclude: Tuple[str, ...] = ('tomo', 'DD_Calib', 'Preset', 'Cluster'),
                   include: Optional[List[str]] = None) -> List[Dict[str, Any]]:
    """Parse metadata from CrysAlisPro experiment directories.
    
    This function extracts comprehensive metadata from various files in experiment
    directories, including XML info files, queue settings, data collection parameters,
    and snapshot images.
    
    Args:
        experiments: Path(s) to experiment folder(s) or CSV file(s)
        log_fun: Logging function (default: print)
        include_merged: Include merged experiments (type 6)
        exclude: Tuple of strings to exclude from experiment names
        include: Optional list of strings that must be in experiment names
    
    Returns:
        List of experiment metadata dicts with keys:
            - path: Experiment path
            - name: Experiment name
            - digest: MD5 hash for stable identification
            - scan_range, detector_distance, indexation, e1, e2, e3: From XML
            - diff_limit, r_int: Data quality metrics
            - stage_x, stage_y, stage_z: Stage positions
            - grain_x_px, grain_y_px: Grain position in pixels
            - aperture_px: Aperture size in pixels
            - diff-<ext>, grain-<ext>, minimap-<ext>, post-<ext>: Snapshot file paths
    
    Example:
        >>> meta = parse_cap_meta('example_data/exp_11317')
        >>> for exp in meta:
        ...     print(f"{exp['name']}: R_int = {exp.get('r_int', 'N/A')}")
    """
    if isinstance(experiments, str):
        experiments = [experiments]
    
    log = print if log_fun is None else log_fun
    
    # Step 1: Collect experiment paths
    exp_list = []
    for exp_entry in experiments:
        if not os.path.exists(exp_entry):
            raise FileNotFoundError(f'Input folder or CSV file {exp_entry} does not exist')
        
        log(f'Scanning {exp_entry}...')
        if exp_entry.endswith('.csv'):
            with open(exp_entry) as fh:
                for _ in range(7):
                    _ = fh.readline()
                ds = list(csv.DictReader(fh))
                new_exp = [os.path.join(d['Dataset path'], d['Experiment name']) for d in ds]
                log(f'Found {len(new_exp)} experiments in CSV')
        else:
            new_exp = [os.path.splitext(fn)[0] for fn in 
                      glob(os.path.join(exp_entry, '**\\*.par'), recursive=True)
                      if '_cracker' not in fn]
            log(f'Found {len(new_exp)} .par files')
        
        exp_list.extend(new_exp)
    
    # Filter experiments
    N = len(exp_list)
    exp_list = [fn for fn in exp_list if all(expr not in fn for expr in exclude)]
    log(f'{N - len(exp_list)} experiments excluded by exclusion list')
    
    if include is not None:
        N = len(exp_list)
        exp_list = [fn for fn in exp_list if any(expr in fn for expr in include)]
        log(f'{N - len(exp_list)} experiments excluded by inclusion list')
    
    exp_list = sorted(list(set(exp_list)))
    log(f'Processing {len(exp_list)} experiments')
    
    # Step 2: Extract metadata
    info = []
    
    for exp in exp_list:
        exp_info = _parse_experiment_metadata(exp, log, include_merged)
        if exp_info is not None:
            info.append(exp_info)
    
    return info


def _parse_experiment_metadata(exp: str, log: Callable,
                               include_merged: bool) -> Optional[Dict[str, Any]]:
    """Parse metadata for a single experiment (helper function)."""
    exp_dir = os.path.dirname(exp)
    
    # Parse XML info file
    info_fn = os.path.join(exp_dir, 'experiment_results.xmlinfo')
    if not os.path.exists(info_fn):
        log(f'WARNING: {info_fn} missing. Skipping.')
        return None
    
    try:
        with open(info_fn) as f:
            info_xml_str = f.read()
        tree = ET.fromstring('<root>\n' + info_xml_str + '\n</root>')
    except Exception as e:
        log(f'ERROR parsing {info_fn}: {e}')
        return None
    
    exp_info = {'path': exp}
    
    # Check experiment type
    if (exp_type := tree.find('__EXPERIMENT_INFO__/__EXPERIMENT_TYPE__')) is not None:
        if exp_type.text and float(exp_type.text) == 6.0 and not include_merged:
            log(f'Skipping merged experiment {exp}')
            return None
    
    # Extract basic info for digest
    user = 'anonymous'
    exp_time = 'unknown time'
    exp_name = os.path.basename(exp)
    
    if (user_elem := tree.find('__EXPERIMENT_INFO__/__USER__')) is not None:
        user = user_elem.text or 'anonymous'
    if (time_elem := tree.find('__EXPERIMENT_INFO__/__START_TIME__')) is not None:
        exp_time = time_elem.text or 'unknown time'
    if (name_elem := tree.find('__EXPERIMENT_INFO__/__EXPERIMENT_PAR_NAME_WOEXT__')) is not None:
        exp_name = name_elem.text or os.path.basename(exp)
    
    exp_info['name'] = exp_name
    
    # Extract XML entries
    xml_fields = {
        'scan_range': '__EXPERIMENT_INFO__/__SCAN_RANGE__',
        'detector_distance': '__EXPERIMENT_INFO__/__DETECTOR_DISTANCE__',
        'indexation': '__EXPERIMENT_RESULTS__/__INDEXATION__',
        'e1': '__EXPERIMENT_RESULTS__/__MOSAICITY__/__MOSAICITY_E1__',
        'e2': '__EXPERIMENT_RESULTS__/__MOSAICITY__/__MOSAICITY_E2__',
        'e3': '__EXPERIMENT_RESULTS__/__MOSAICITY__/__MOSAICITY_E3__',
        'diff_limit': '__EXPERIMENT_RESULTS__/__DIFFLIMIT__',
        'r_int': '__EXPERIMENT_RESULTS__/__RINT__',
        'stage_x': '__EXPERIMENT_INFO__/__STAGE_POSITION__/__STAGE_POSITION_X__',
        'stage_y': '__EXPERIMENT_INFO__/__STAGE_POSITION__/__STAGE_POSITION_Y__',
        'stage_z': '__EXPERIMENT_INFO__/__STAGE_POSITION__/__STAGE_POSITION_Z__',
    }
    
    for key, xpath in xml_fields.items():
        elem = tree.find(xpath)
        if elem is not None and elem.text:
            try:
                exp_info[key] = float(elem.text)
            except ValueError:
                pass
    
    # Generate stable digest
    m = hashlib.md5()
    m.update(f'{user};{exp_time};{exp_name}'.encode())
    exp_info['digest'] = m.hexdigest()
    
    # Parse queue info file
    xpos, ypos = 387.5, 192.5
    qed_file = os.path.join(exp_dir, 'metadataexpsettings.qed')
    if os.path.exists(qed_file):
        try:
            with open(qed_file, 'r') as fh:
                for ln in fh:
                    if 'la_abspixelrequestedposition_xy2[0]' in ln:
                        xpos = int(ln.split('=')[1].strip())
                    elif 'la_abspixelrequestedposition_xy2[1]' in ln:
                        ypos = int(ln.split('=')[1].strip())
        except Exception:
            pass
    
    exp_info['grain_x_px'] = xpos
    exp_info['grain_y_px'] = ypos
    
    # Parse data collection ini file
    try:
        config = configparser.ConfigParser()
        ini_path = os.path.join(exp_dir, 'expinfo', f'{exp_name}_datacoll.ini')
        config.read(ini_path)
        
        OL_demag, visual_pxs = 47, 0.036
        aperture_info = config['MicroED'].get('Aperture SA info', None)
        if aperture_info:
            exp_info['aperture_px'] = float(aperture_info) / OL_demag / visual_pxs
        else:
            exp_info['aperture_px'] = -1
    except Exception:
        exp_info['aperture_px'] = -1
    
    # Find snapshot files
    extensions = ['rodhypix', 'jpg', 'tiff']
    kinds = {
        'diff': 'middle_microed_diff_snapshot',
        'grain': 'microed_grain_snapshot',
        'minimap': 'microed_minimap_snapshot',
        'post': 'microed_post_snapshot'
    }
    
    for kind, fn_label in kinds.items():
        for ext in extensions:
            fn = os.path.join(exp_dir, f'{exp_name}_{fn_label}.{ext}')
            if os.path.exists(fn):
                exp_info[f'{kind}-{ext}'] = fn
    
    return exp_info


# ============================================================================
# XML Parameter File Classes
# ============================================================================

class ProffitXML:
    """Handler for CrysAlisPro data reduction (proffit) XML parameter files.
    
    These files are used with the commands:
        DC PROFFIT XML <xml_file>           # Run data reduction with XML settings
        XX PARTOXML <pars_file> [<xml_file>]  # Convert .proffitpars to XML
    
    Args:
        filename: Path to XML file
        path: Experiment path (without extension) for input/output settings
        allow_missing: If True, allow creation without existing file
        parse: If True, parse file immediately
    
    Example:
        >>> prof = ProffitXML('exp_11317.xml', 'exp_11317')
        >>> prof.set_parameters(d_min=0.8, laue=5, gral_mode=1)
        >>> # Now run: cap.execute(f'dc proffit xml {prof.filename}')
    """
    
    def __init__(self, filename: str, path: str,
                 allow_missing: bool = False, parse: bool = True):
        self.filename = filename
        self.path = path
        self.full_path = os.path.join(path, filename) if path else filename
        self.tree = None
        if parse:
            self.update(allow_missing)
    
    def update(self, allow_missing: bool = False) -> None:
        """Reload parameters from XML file."""
        try:
            self.tree = ET.parse(self.full_path)
        except FileNotFoundError:
            if allow_missing:
                self.tree = None
            else:
                raise FileNotFoundError(f'Proffit XML file {self.full_path} does not exist')
    
    def set_parameters(self, template: Optional[str] = None,
                      laue: Optional[int] = None,
                      friedel_mates: Optional[bool] = None,
                      scan_width: Optional[float] = None,
                      d_min: Optional[float] = None,
                      d_max: Optional[float] = None,
                      gral_mode: Optional[int] = None,
                      autochem: Optional[bool] = None,
                      **kwargs: str) -> None:
        """Set proffit parameters.
        
        Args:
            template: Path to template XML file to copy from
            laue: Laue group index (0-18)
            friedel_mates: Enable Friedel mate treatment
            scan_width: Scan width in degrees
            d_min: Minimum d-spacing for processing
            d_max: Maximum d-spacing for processing
            gral_mode: GRAL mode (0=OFF, 1=ONAUTO, 2=MANUAL)
            autochem: Enable AutoChem structure solution
            **kwargs: Additional XML path/value pairs as 'xpath': 'value'
        """
        if template is not None:
            if os.path.exists(template):
                tree = ET.parse(template)
            else:
                raise FileNotFoundError(f'Template file {template} does not exist')
        elif self.tree is not None:
            tree = self.tree
        else:
            raise ValueError('No parameters loaded; please specify a template')
        
        root = tree.getroot()
        
        # Set parameters
        pars = dict(kwargs)
        
        if laue is not None:
            pars['__PROFFIT__PARAMETERS__/__Type_of_Laue__'] = str(laue)
        if friedel_mates is not None:
            pars['__PROFFIT__PARAMETERS__/__Is_Friedel_mate_on__'] = '1' if friedel_mates else '0'
        if scan_width is not None:
            pars['__PROFFIT__PARAMETERS__/__Scan_width_in_deg__'] = str(scan_width)
        if d_min is not None:
            pars['__PROFFIT__PARAMETERS__/__dmin__'] = str(d_min)
        if d_max is not None:
            pars['__PROFFIT__PARAMETERS__/__dmax__'] = str(d_max)
        if gral_mode is not None:
            pars['__PROFFIT__PARAMETERS__/__Gral_mode__'] = str(gral_mode)
        if autochem is not None:
            pars['__PROFFIT__PARAMETERS__/__Is_AUTOCHEM__'] = '1' if autochem else '0'
        
        # Apply all parameters
        for xpath, value in pars.items():
            elem = root.find(xpath)
            if elem is not None:
                elem.text = value
            else:
                warnings.warn(f'XML path not found: {xpath}')
        
        self.tree = tree
        
        if self.filename:
            tree.write(self.full_path)


class FinalizationXML:
    """Handler for CrysAlisPro finalization XML parameter files.
    
    These files are used with the commands:
        DC RRPFROMXML <xml_file>           # Finalize using XML settings
        DC XMLRRP [input] [output_xml]     # Save finalization dialog to XML
    
    Args:
        filename: Path to XML file
        path: Experiment path (without extension) for input/output settings
        allow_missing: If True, allow creation without existing file
        parse: If True, parse file immediately
    
    Example:
        >>> fin = FinalizationXML('exp_11317_finalizer.xml', 'exp_11317')
        >>> fin.set_parameters(gral=True, res_limit=0.7, N_shells=15)
        >>> # Now run: cap.execute(f'dc rrpfromxml {fin.filename}')
    """
    
    def __init__(self, filename: str, path: str,
                 allow_missing: bool = False, parse: bool = True):
        self.filename = filename
        self.path = path
        self.full_path = os.path.join(os.path.dirname(path), filename)
        self.tree = None
        if parse:
            self.update(allow_missing)
    
    def update(self, allow_missing: bool = False) -> None:
        """Reload parameters from XML file."""
        try:
            self.tree = ET.parse(self.full_path)
        except FileNotFoundError:
            if allow_missing:
                self.tree = None
            else:
                raise FileNotFoundError(f'Finalization XML file {self.full_path} does not exist')
    
    def set_parameters(self, template: Optional[str] = None,
                      gral: Optional[bool] = None,
                      gral_interactive: Optional[bool] = None,
                      autochem: Optional[bool] = None,
                      laue: Optional[Union[int, str]] = None,
                      z: Optional[float] = None,
                      chem: Optional[str] = None,
                      res_limit: Optional[float] = None,
                      fom: Tuple[str, ...] = ('Rint', 'Rurim', 'Rpim', 'CC 1/2', 'deltaCC',
                                              'Sigma', 'SigmaA', 'SigmaB', 'CC*'),
                      N_shells: int = 10,
                      pars: Optional[Dict[str, str]] = None) -> None:
        """Set finalization parameters.
        
        Args:
            template: Path to template XML file to copy from
            gral: Enable GRAL space group determination
            gral_interactive: Use interactive GRAL mode (not recommended for automation)
            autochem: Enable AutoChem structure solution
            laue: Laue group (int index or string name)
            z: Number of formula units in unit cell
            chem: Chemical formula
            res_limit: High resolution limit (Angstroms)
            fom: Tuple of figure-of-merit names for output
            N_shells: Number of resolution shells for statistics
            pars: Additional XML path/value pairs
        """
        if template is not None:
            if os.path.exists(template):
                tree = ET.parse(template)
            else:
                raise FileNotFoundError(f'Template file {template} does not exist')
        elif self.tree is not None:
            tree = self.tree
        else:
            raise ValueError('No parameters loaded; please specify a template')
        
        root = tree.getroot()
        
        # Set file paths
        root.find('__FINALIZER_SAMPLE__/__Input_file__').text = os.path.basename(self.path)
        root.find('__FINALIZER_SAMPLE__/__Input_file_path__').text = os.path.dirname(self.path)
        root.find('__FINALIZER_OUTPUT__/__Output_file__').text = os.path.basename(self.path)
        root.find('__FINALIZER_OUTPUT__/__Output_file_path__').text = self.path
        
        pars = pars or {}
        
        if gral is not None:
            pars['__FINALIZER_SPACE_GROUP_AND_AUTOCHEM__/__Is_GRAL_on__'] = '1' if gral else '0'
        if gral_interactive is not None:
            pars['__FINALIZER_SPACE_GROUP_AND_AUTOCHEM__/__GRAL_mode__'] = '1' if gral_interactive else '0'
        if autochem is not None:
            pars['__FINALIZER_SPACE_GROUP_AND_AUTOCHEM__/__Is_AutoChem_active__'] = '1' if autochem else '0'
        if laue is not None:
            if isinstance(laue, str):
                # Parse laue index from indexinfo
                indexinfo = root.find('__FINALIZER_SAMPLE__/__Type_of_Laue__indexinfo__')
                if indexinfo is not None and indexinfo.text:
                    laue_map = {v.strip(): int(k) for k, v in 
                               (entry.split('-', 1) for entry in indexinfo.text.split(';'))}
                    laue = laue_map.get(laue, 0)
            pars['__FINALIZER_SAMPLE__/__Type_of_Laue__'] = str(laue)
        if res_limit is not None:
            pars['__FINALIZER_FILTERS_AND_LIMITS__/__Automated__'] = '0'
            pars['__FINALIZER_FILTERS_AND_LIMITS__/__Apply_resolution_limits__'] = '1'
            pars['__FINALIZER_FILTERS_AND_LIMITS__/__Resolution_limits_-_high_limit__'] = str(res_limit)
            pars['__FINALIZER_FILTERS_AND_LIMITS__/__Dmin_for_completness__'] = str(res_limit)
        if z is not None:
            pars['__FINALIZER_SAMPLE__/__Z__'] = str(z)
        if chem is not None:
            pars['__FINALIZER_SAMPLE__/__Chemical_formula__'] = str(chem)
        
        # Set shell and FOM parameters
        pars['__FINALIZER_FILTERS_AND_LIMITS__/__Apply_printout_options__'] = '1'
        pars['__FINALIZER_FILTERS_AND_LIMITS__/__Printout_options_-_number_of_shells__'] = str(N_shells)
        
        for i, fom_name in enumerate(fom):
            fom_idx = _FOM_DICT.get(fom_name, 0)
            pars[f'__FINALIZER_FILTERS_AND_LIMITS__/__Printout_options_-_Output_order_-_{i}__'] = str(fom_idx)
        
        # Apply all parameters
        for xpath, value in pars.items():
            elem = root.find(xpath)
            if elem is not None:
                elem.text = value
            else:
                warnings.warn(f'XML path not found: {xpath}')
        
        self.tree = tree
        
        if self.filename:
            tree.write(self.full_path)
